version: "3.8"

services:
    app:
        build: 
            context: .
            dockerfile: ./Dockerfile
        image: api-test
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        environment: 
            PORT: 8000
            PYTHONUNBUFFERED: 1